[package]
name = "bevy-explorer"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

[dependencies]
crossbow  = "0.1.3"
anyhow = "1.0"
subxt = "0.23.0"
tokio = { version = "1.17", features = ["sync", "macros", "rt-multi-thread"] }
bevy = { version = "0.8.1", default-features = false, features = ["bevy_winit", "render", "bevy_asset"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
jsonrpsee = { version = "0.15.1", features = ["async-client", "client-ws-transport"] }

[package.metadata]
app_name = "Bevy Explorer"
assets = ["assets"]

[package.metadata.android]
app_wrapper = "ndk-glue"
release_build_targets = ["aarch64-linux-android"]
resources = ["assets/res/android"]

[package.metadata.apple]
release_build_targets = ["aarch64-apple-ios", "x86_64-apple-ios"]
resources = ["assets/res/apple"]

[package.metadata.android.manifest]
package = "com.crossbow.example.permissions"

[[package.metadata.android.manifest.uses_permission]]
name = "android.permission.INTERNET"