[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

[dependencies]
crossbow = "*"
log = "0.4"
anyhow = "1.0"
macroquad = "0.3"

[package.metadata]
app_name = "{{project-name}}"
assets = ["assets"]

[package.metadata.android]
release_build_targets = ["aarch64-linux-android"]
resources = ["res/android"]

[package.metadata.apple]
release_build_targets = ["aarch64-apple-ios", "x86_64-apple-ios"]
resources = ["res/apple"]
