[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

[dependencies]
crossbow = "*"
log = "0.4"
anyhow = "1.0"
macroquad = "0.3"

[package.metadata.android]
app_name = "{{project-name}}"
target_sdk_version = 30
version_code = 1
icon = "ic_launcher"

build_targets = ["aarch64-linux-android"]
assets = "assets"
res = "res/android"

[package.metadata.apple]
app_name = "{{project-name}}"
build_targets = ["aarch64-apple-ios", "x86_64-apple-ios"]
assets = "assets"
res = "res/apple"
