[package]
name = "project_name"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

[dependencies]
crossbow = { git = "https://github.com/dodorare/crossbow" }

[package.metadata]
icon = "ic_launcher"
android_res = "res/android"
apple_res = "res/apple"
